on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Prepare Release

defaults:
  run:
    shell: bash

jobs:
  prepare_release:
    permissions: write-all
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Create a single instance for all uploads.
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body: |
            GitHub Actions created release.
  create_release:
    permissions: write-all
    name: Upload Releases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build project
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m build -o ./dist
      - name: Upload source to Release Draft
        uses: softprops/action-gh-release@v2
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12' }}
        with:
          files: ./dist/*.tar.gz
          draft: true
          body: |
            GitHub Actions created release.
      - name: Upload whl to Release Draft
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*.whl 
          draft: true
          body: |
            GitHub Actions created release.
