# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build pyyield Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.x
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        pip install -r requirements.txt
    - name: Lint
      run: |
        # stop the build if there are Python syntax errors or undefined names
        python -m black -v --check .
        # TODO: Lint with clang-format for .cpp
    - name: Build
      run: |
        python -m build -o ./dist
        # ls dist
        pip install ./dist/pyyield*.whl
    - name: Test with pytest
      run: |
        pytest --verbose --log-cli-level=DEBUG
